# Generated by Django 5.1.3 on 2024-11-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='description',
            new_name='discription',
        ),
    ]
