# Generated by Django 5.1.3 on 2024-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0002_rename_description_moviedata_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
