# Generated by Django 5.1.3 on 2024-11-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0004_alter_moviedata_discription_alter_moviedata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='discription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='year',
            field=models.IntegerField(max_length=200),
        ),
    ]
