# Generated by Django 5.1.3 on 2024-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0005_alter_moviedata_discription_alter_moviedata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
