# Generated by Django 5.1.3 on 2024-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0006_alter_moviedata_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
