# Generated by Django 5.1.3 on 2024-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Manager', '0007_moviedata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
